clc;clear;

%% Define parameters and variables:
d1=0.36;
d3=0.42;
d5=0.4;
d7=0.131;

% q = sym('q',[7,1]);
% v = ...
% dq= ...


%% Define the function for Transformation and Rotation matrices:
% T = @(a,al,d,th)([cos(th) .....
% R = ....

%% Define the transformation matrices and rotation matrices:
% T1 = ...
% T2 = ....
% ....

% R1 = ...
% ...

%% Define Z vector and P vectors:
% Z0 = [0;0;1];
% Z1 = .....
% .....

% Po = [0;0;0;1];
% P0 = Po(1:3);
% P1t = ....
% .....
 
% J_temp = [cross(Z0,(P7-P0)),...

digits(10);
J=dre(vpa(J_temp));

matlabFunction(J,'File','Jacobian_KUKA7','Vars',{q});
% matlabFunction(P7,'File','KUKA_FKin','Vars',{q});