function out1 = A_0_e_omni_bundle_fun(in1)
%A_0_E_OMNI_BUNDLE_FUN
%    OUT1 = A_0_E_OMNI_BUNDLE_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    09-Mar-2019 12:28:51

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t5 = pi./2.0;
t3 = q3-t5;
t4 = cos(q2);
t6 = sin(t3);
t7 = cos(t3);
t8 = sin(q2);
t9 = sin(q1);
out1 = reshape([t2.*t4.*t7-t2.*t6.*t8,t4.*t7.*t9-t6.*t8.*t9,-t4.*t6-t7.*t8,0.0,-t2.*t4.*t6-t2.*t7.*t8,-t4.*t6.*t9-t7.*t8.*t9,-t4.*t7+t6.*t8,0.0,-t9,t2,0.0,0.0,t2.*t4.*(1.3e1./1.0e2)+t2.*t4.*t7.*(1.3e1./1.0e2)-t2.*t6.*t8.*(1.3e1./1.0e2),t4.*t9.*(1.3e1./1.0e2)+t4.*t7.*t9.*(1.3e1./1.0e2)-t6.*t8.*t9.*(1.3e1./1.0e2),t8.*(-1.3e1./1.0e2)-t4.*t6.*(1.3e1./1.0e2)-t7.*t8.*(1.3e1./1.0e2),1.0],[4,4]);
