function out1 = dJ_analit_P_omni_bundle_fun(in1,in2)
%DJ_ANALIT_P_OMNI_BUNDLE_FUN
%    OUT1 = DJ_ANALIT_P_OMNI_BUNDLE_FUN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Mar-2019 08:24:47

dq1 = in2(1,:);
dq2 = in2(2,:);
dq3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q2+q3;
t3 = sin(q1);
t4 = cos(t2);
t5 = cos(q1);
t6 = sin(t2);
t7 = t6.*(1.3e1./1.0e2);
t8 = cos(q2);
t9 = t8.*(1.3e1./1.0e2);
t10 = t7+t9;
t11 = t4.*(1.3e1./1.0e2);
t12 = sin(q2);
t14 = t12.*(1.3e1./1.0e2);
t13 = t11-t14;
out1 = reshape([dq3.*t3.*t4.*(-1.3e1./1.0e2)-dq1.*t5.*t10-dq2.*t3.*t13,dq3.*t4.*t5.*(1.3e1./1.0e2)-dq1.*t3.*t10+dq2.*t5.*t13,0.0,0.0,0.0,0.0,dq3.*t5.*t6.*(-1.3e1./1.0e2)-dq1.*t3.*t13-dq2.*t5.*t10,dq3.*t3.*t6.*(-1.3e1./1.0e2)-dq2.*t3.*t10+dq1.*t5.*t13,dq3.*t4.*(-1.3e1./1.0e2)-dq2.*t13],[3,3]);
